import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Trans } from '@lingui/macro';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js with LinguiJS i18n</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Trans>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </Trans>
        </h1>

        <div className={styles.grid}>
          <Link href="." locale="en">
            <a className={styles.card}>
              <h2>English</h2>
              <p>Switch to english</p>
            </a>
          </Link>
          <Link href="." locale="hr">
            <a className={styles.card}>
              <h2>hrvatski</h2>
              <p>Switch to Croatian</p>
            </a>
          </Link>
          <Link href="." locale="de">
            <a className={styles.card}>
              <h2>Deutsch</h2>
              <p>Switch to german</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
